import { Footer, Header } from '@/components';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Car hub',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={'relative overflow-x-hidden'}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
